// ─────────────────────────────────────────────────────────────────────────────
// mockEmployees.ts — Datos de ejemplo para el Directorio
// Reemplazar con llamada a Microsoft Graph: GET /v1.0/users?$select=...
// ─────────────────────────────────────────────────────────────────────────────

import { Employee } from "./types";

export const MOCK_EMPLOYEES: Employee[] = [
  // ── Dirección General ───────────────────────────────────────────────────────
  {
    id: "1",
    displayName: "Carlos Mendoza Ríos",
    firstName: "Carlos",
    lastName: "Mendoza Ríos",
    jobTitle: "Director General",
    department: "Dirección General",
    mail: "c.mendoza@empresa.com",
    mobilePhone: "+57 310 234 5678",
    businessPhone: "+57 1 234 5678",
    extension: "1000",
    officeLocation: "Piso 10 — Torre Principal",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2015-03-01",
    managerName: null,
  },
  {
    id: "2",
    displayName: "Valentina Ospina Rueda",
    firstName: "Valentina",
    lastName: "Ospina Rueda",
    jobTitle: "Directora de Operaciones",
    department: "Dirección General",
    mail: "v.ospina@empresa.com",
    mobilePhone: "+57 315 876 5432",
    businessPhone: "+57 1 234 5679",
    extension: "1001",
    officeLocation: "Piso 10 — Torre Principal",
    city: "Bogotá",
    photo: null,
    status: "remote",
    hireDate: "2016-07-15",
    managerName: "Carlos Mendoza Ríos",
  },

  // ── TI ──────────────────────────────────────────────────────────────────────
  {
    id: "3",
    displayName: "Andrés Felipe Torres",
    firstName: "Andrés Felipe",
    lastName: "Torres",
    jobTitle: "Líder de Tecnología",
    department: "TI",
    mail: "af.torres@empresa.com",
    mobilePhone: "+57 300 111 2233",
    businessPhone: "+57 1 234 5680",
    extension: "2000",
    officeLocation: "Piso 3 — Sala de Servidores",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2018-01-10",
    managerName: "Valentina Ospina Rueda",
  },
  {
    id: "4",
    displayName: "Laura Camila Suárez",
    firstName: "Laura Camila",
    lastName: "Suárez",
    jobTitle: "Desarrolladora Full Stack",
    department: "TI",
    mail: "lc.suarez@empresa.com",
    mobilePhone: "+57 312 444 5566",
    businessPhone: null,
    extension: "2001",
    officeLocation: "Piso 3 — Open Space",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2021-03-22",
    managerName: "Andrés Felipe Torres",
  },
  {
    id: "5",
    displayName: "Sebastián Gómez Parra",
    firstName: "Sebastián",
    lastName: "Gómez Parra",
    jobTitle: "DevOps Engineer",
    department: "TI",
    mail: "s.gomez@empresa.com",
    mobilePhone: "+57 320 777 8899",
    businessPhone: null,
    extension: "2002",
    officeLocation: "Piso 3 — Open Space",
    city: "Bogotá",
    photo: null,
    status: "remote",
    hireDate: "2022-09-05",
    managerName: "Andrés Felipe Torres",
  },

  // ── Recursos Humanos ────────────────────────────────────────────────────────
  {
    id: "6",
    displayName: "María José Herrera",
    firstName: "María José",
    lastName: "Herrera",
    jobTitle: "Directora de Recursos Humanos",
    department: "Recursos Humanos",
    mail: "mj.herrera@empresa.com",
    mobilePhone: "+57 311 222 3344",
    businessPhone: "+57 1 234 5681",
    extension: "3000",
    officeLocation: "Piso 5 — Sala de Bienestar",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2017-05-20",
    managerName: "Carlos Mendoza Ríos",
  },
  {
    id: "7",
    displayName: "Juan Pablo Rincón",
    firstName: "Juan Pablo",
    lastName: "Rincón",
    jobTitle: "Analista de Selección",
    department: "Recursos Humanos",
    mail: "jp.rincon@empresa.com",
    mobilePhone: "+57 318 555 6677",
    businessPhone: null,
    extension: "3001",
    officeLocation: "Piso 5",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2020-02-14",
    managerName: "María José Herrera",
  },

  // ── Finanzas ────────────────────────────────────────────────────────────────
  {
    id: "8",
    displayName: "Ricardo Alejandro Mora",
    firstName: "Ricardo Alejandro",
    lastName: "Mora",
    jobTitle: "Director Financiero",
    department: "Finanzas",
    mail: "ra.mora@empresa.com",
    mobilePhone: "+57 301 888 9900",
    businessPhone: "+57 1 234 5682",
    extension: "4000",
    officeLocation: "Piso 8 — Sala Financiera",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2014-11-01",
    managerName: "Carlos Mendoza Ríos",
  },
  {
    id: "9",
    displayName: "Diana Carolina Peña",
    firstName: "Diana Carolina",
    lastName: "Peña",
    jobTitle: "Contadora Senior",
    department: "Finanzas",
    mail: "dc.pena@empresa.com",
    mobilePhone: "+57 314 321 0987",
    businessPhone: null,
    extension: "4001",
    officeLocation: "Piso 8",
    city: "Bogotá",
    photo: null,
    status: "vacation",
    hireDate: "2019-08-12",
    managerName: "Ricardo Alejandro Mora",
  },

  // ── Jurídica ────────────────────────────────────────────────────────────────
  {
    id: "10",
    displayName: "Camila Fernanda Vargas",
    firstName: "Camila Fernanda",
    lastName: "Vargas",
    jobTitle: "Directora Jurídica",
    department: "Jurídica",
    mail: "cf.vargas@empresa.com",
    mobilePhone: "+57 317 654 3210",
    businessPhone: "+57 1 234 5683",
    extension: "5000",
    officeLocation: "Piso 9 — Área Legal",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2016-04-18",
    managerName: "Carlos Mendoza Ríos",
  },
  {
    id: "11",
    displayName: "Felipe Antonio Castro",
    firstName: "Felipe Antonio",
    lastName: "Castro",
    jobTitle: "Abogado Corporativo",
    department: "Jurídica",
    mail: "fa.castro@empresa.com",
    mobilePhone: "+57 302 147 2589",
    businessPhone: null,
    extension: "5001",
    officeLocation: "Piso 9",
    city: "Bogotá",
    photo: null,
    status: "away",
    hireDate: "2021-10-05",
    managerName: "Camila Fernanda Vargas",
  },

  // ── Comercial ───────────────────────────────────────────────────────────────
  {
    id: "12",
    displayName: "Santiago Reyes Forero",
    firstName: "Santiago",
    lastName: "Reyes Forero",
    jobTitle: "Director Comercial",
    department: "Comercial",
    mail: "s.reyes@empresa.com",
    mobilePhone: "+57 319 963 8520",
    businessPhone: "+57 1 234 5684",
    extension: "6000",
    officeLocation: "Piso 6 — Sala Comercial",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2015-09-30",
    managerName: "Valentina Ospina Rueda",
  },
  {
    id: "13",
    displayName: "Natalia Gómez Díaz",
    firstName: "Natalia",
    lastName: "Gómez Díaz",
    jobTitle: "Ejecutiva de Ventas",
    department: "Comercial",
    mail: "n.gomez@empresa.com",
    mobilePhone: "+57 313 741 8520",
    businessPhone: null,
    extension: "6001",
    officeLocation: "Piso 6",
    city: "Medellín",
    photo: null,
    status: "remote",
    hireDate: "2022-01-17",
    managerName: "Santiago Reyes Forero",
  },
  {
    id: "14",
    displayName: "Daniela Ramírez Agudelo",
    firstName: "Daniela",
    lastName: "Ramírez Agudelo",
    jobTitle: "Gerente de Cuentas Clave",
    department: "Comercial",
    mail: "d.ramirez@empresa.com",
    mobilePhone: "+57 316 852 9630",
    businessPhone: null,
    extension: "6002",
    officeLocation: "Piso 6",
    city: "Cali",
    photo: null,
    status: "active",
    hireDate: "2020-06-01",
    managerName: "Santiago Reyes Forero",
  },

  // ── eCommerce ───────────────────────────────────────────────────────────────
  {
    id: "15",
    displayName: "Miguel Ángel Rodríguez",
    firstName: "Miguel Ángel",
    lastName: "Rodríguez",
    jobTitle: "Head of eCommerce",
    department: "eCommerce",
    mail: "ma.rodriguez@empresa.com",
    mobilePhone: "+57 321 159 7531",
    businessPhone: "+57 1 234 5685",
    extension: "7000",
    officeLocation: "Piso 4 — Digital Hub",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2019-03-11",
    managerName: "Valentina Ospina Rueda",
  },
  {
    id: "16",
    displayName: "Isabella Castaño Mejía",
    firstName: "Isabella",
    lastName: "Castaño Mejía",
    jobTitle: "Especialista en Pauta Digital",
    department: "eCommerce",
    mail: "i.castano@empresa.com",
    mobilePhone: "+57 322 268 4620",
    businessPhone: null,
    extension: "7001",
    officeLocation: "Piso 4 — Digital Hub",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2023-02-06",
    managerName: "Miguel Ángel Rodríguez",
  },

  // ── Logística ───────────────────────────────────────────────────────────────
  {
    id: "17",
    displayName: "Hernando Bejarano López",
    firstName: "Hernando",
    lastName: "Bejarano López",
    jobTitle: "Director de Logística",
    department: "Logística",
    mail: "h.bejarano@empresa.com",
    mobilePhone: "+57 303 357 9753",
    businessPhone: "+57 1 234 5686",
    extension: "8000",
    officeLocation: "Bodega Principal — Zona Franca",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2013-07-22",
    managerName: "Valentina Ospina Rueda",
  },
  {
    id: "18",
    displayName: "Paola Andrea Nieto",
    firstName: "Paola Andrea",
    lastName: "Nieto",
    jobTitle: "Coordinadora de Inventario",
    department: "Logística",
    mail: "pa.nieto@empresa.com",
    mobilePhone: "+57 309 446 8642",
    businessPhone: null,
    extension: "8001",
    officeLocation: "Bodega Principal",
    city: "Bogotá",
    photo: null,
    status: "vacation",
    hireDate: "2020-11-30",
    managerName: "Hernando Bejarano López",
  },

  // ── Tiendas ─────────────────────────────────────────────────────────────────
  {
    id: "19",
    displayName: "Gloria Esperanza Soto",
    firstName: "Gloria Esperanza",
    lastName: "Soto",
    jobTitle: "Directora de Tiendas",
    department: "Tiendas",
    mail: "ge.soto@empresa.com",
    mobilePhone: "+57 306 535 7531",
    businessPhone: "+57 1 234 5687",
    extension: "9000",
    officeLocation: "CC Gran Estación — Local 120",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2016-02-08",
    managerName: "Valentina Ospina Rueda",
  },
  {
    id: "20",
    displayName: "David Andrés Pinto",
    firstName: "David Andrés",
    lastName: "Pinto",
    jobTitle: "Supervisor de Tienda Norte",
    department: "Tiendas",
    mail: "da.pinto@empresa.com",
    mobilePhone: "+57 308 624 6420",
    businessPhone: null,
    extension: "9001",
    officeLocation: "CC Santa Fe — Local 315",
    city: "Bogotá",
    photo: null,
    status: "active",
    hireDate: "2021-07-19",
    managerName: "Gloria Esperanza Soto",
  },
  {
    id: "21",
    displayName: "Alejandra Lucía Montoya",
    firstName: "Alejandra Lucía",
    lastName: "Montoya",
    jobTitle: "Asesora Comercial Tiendas",
    department: "Tiendas",
    mail: "al.montoya@empresa.com",
    mobilePhone: "+57 304 713 5319",
    businessPhone: null,
    extension: "9002",
    officeLocation: "CC Andino — Local 210",
    city: "Bogotá",
    photo: null,
    status: "remote",
    hireDate: "2023-05-02",
    managerName: "Gloria Esperanza Soto",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

export function getEmployeesByDepartment(department: string): Employee[] {
  if (department === "Todos") return MOCK_EMPLOYEES;
  return MOCK_EMPLOYEES.filter((e) => e.department === department);
}

export function searchEmployees(query: string, employees: Employee[]): Employee[] {
  const q = query.toLowerCase().trim();
  if (!q) return employees;
  return employees.filter(
    (e) =>
      e.displayName.toLowerCase().includes(q) ||
      e.jobTitle.toLowerCase().includes(q) ||
      e.department.toLowerCase().includes(q) ||
      e.mail.toLowerCase().includes(q) ||
      e.city?.toLowerCase().includes(q) ||
      e.officeLocation?.toLowerCase().includes(q)
  );
}

export const DEPARTMENT_COLORS: Record<string, string> = {
  "Dirección General": "#1e3a5f",
  "TI":                "#0ea5e9",
  "Recursos Humanos":  "#8b5cf6",
  "Finanzas":          "#10b981",
  "Jurídica":          "#f59e0b",
  "Comercial":         "#ef4444",
  "eCommerce":         "#f97316",
  "Logística":         "#6366f1",
  "Tiendas":           "#ec4899",
};