import type { QuickLinkConfig } from "@/lib/quickLinksAccess";

export const financeQuickLinks: QuickLinkConfig[] = [
  { label: "Presupuesto",  href: "/finance/budget",   icon: "PieChart",   color: "purple",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Solo el equipo de Finanzas puede acceder al presupuesto" },
  { label: "Gastos",       href: "/finance/expenses", icon: "Receipt",    color: "amber",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Solo el equipo de Finanzas puede gestionar gastos" },
  { label: "Tesorería",    href: "/finance/treasury", icon: "Landmark",   color: "teal",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Acceso restringido al equipo de Finanzas" },
  { label: "Reportes",     href: "/finance/reports",  icon: "BarChart2",  color: "blue",
    requiredPermission: "finance:view_reports" },
  { label: "Pagos",        href: "/finance/payments", icon: "CreditCard", color: "green",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Solo el equipo de Finanzas puede gestionar pagos" },
  { label: "Proveedores",  href: "/finance/vendors",  icon: "Users",      color: "coral",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Acceso restringido al equipo de Finanzas" },
  { label: "Facturas",     href: "/finance/invoices", icon: "FileText",   color: "purple",
    requiredPermission: "finance:view_kpis",     enabledPermission: "finance:view_modules",
    disabledMsg: "Solo el equipo de Finanzas puede ver facturas" },
  { label: "Proyecciones", href: "/finance/forecast", icon: "TrendingUp", color: "blue",
    requiredPermission: "finance:view_dashboard", enabledPermission: "finance:view_modules",
    disabledMsg: "Acceso restringido al equipo de Finanzas" },
];